<?php
/**
 * Static Terms of Service - publicly accessible (no auth).
 *
 * Routed from index.php at GET /app/terms. Uses the app layout shell
 * (html_open / html_close) but no authenticated nav. Terms text is embedded
 * directly below; update the "Last Updated" line when the text changes.
 *
 * Style mirrors views/static/privacy.php (teal headings, 720px centered column).
 */
require_once __DIR__ . '/../../views/layout/base.php';

$pageTitle = 'Terms of Service';
$extraCss  = <<<CSS
<style>
    .terms-page {
        max-width: 720px;
        margin: 0 auto;
        padding: 48px 20px 96px;
        line-height: 1.65;
    }
    .terms-page h1 {
        color: var(--accent-mid);
        font-size: 28px;
        font-weight: 700;
        letter-spacing: -0.02em;
        margin-bottom: 6px;
    }
    .terms-page .terms-effective {
        color: var(--text-muted);
        font-size: 13px;
        margin-bottom: 32px;
    }
    .terms-page h2 {
        color: var(--accent-mid);
        font-size: 19px;
        font-weight: 600;
        margin: 32px 0 10px;
    }
    .terms-page h3 {
        font-size: 15px;
        font-weight: 600;
        margin: 20px 0 6px;
    }
    .terms-page p,
    .terms-page li {
        font-size: 15px;
        color: var(--text-primary);
    }
    .terms-page ul {
        margin: 8px 0 8px 22px;
    }
    .terms-page li { margin-bottom: 6px; }
    .terms-page a { color: var(--accent-mid); }
    .terms-page strong { font-weight: 600; }
</style>
CSS;

include __DIR__ . '/../../views/layout/html_open.php';
?>
<main class="terms-page">
    <h1>SimplyRunFaster Terms of Service</h1>
    <p class="terms-effective">Effective Date: June 17, 2026 &middot; Last Updated: June 17, 2026</p>

    <h2>1. Acceptance of Terms</h2>
    <p>
        By creating an account on SimplyRunFaster (&ldquo;the Platform&rdquo;), you agree to these
        Terms of Service (&ldquo;Terms&rdquo;). If you do not agree, do not use the Platform. By
        checking the acceptance box during onboarding, you confirm you have read, understood, and
        agree to these Terms.
    </p>
    <p>
        These Terms constitute a legally binding agreement between you and Will Musto, operating as
        SimplyRunFaster (&ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;), a sole proprietorship
        based in Chattanooga, Tennessee.
    </p>

    <h2>2. Eligibility</h2>
    <p>
        You must be 18 years of age or older, or have verifiable parental or guardian consent, to use
        the Platform. By creating an account, you confirm that you meet this requirement.
    </p>

    <h2>3. Description of Service</h2>
    <p>
        SimplyRunFaster is a running coaching platform that combines algorithmic training plan
        generation with human coach oversight. Specifically:
    </p>
    <ul>
        <li>Training plans are generated by an automated engine based on information you provide
            during onboarding (fitness level, goal race, availability, and other inputs).</li>
        <li>All algorithmically generated plans are reviewed and approved by a human coach before
            being made visible to you. You will never receive a plan that has not been reviewed by
            your assigned coach.</li>
        <li>Coaches communicate with athletes through the Platform's in-app messaging system.</li>
        <li>Training data from connected devices (via Intervals.icu) may be used to inform plan
            adjustments.</li>
    </ul>
    <p>
        SimplyRunFaster is a coaching assistance platform. It is not a medical service, physical
        therapy service, or substitute for professional medical advice.
    </p>

    <h2>4. Not Medical Advice</h2>
    <p>
        The training plans, coaching communications, and all content provided through SimplyRunFaster
        are for informational and educational purposes only and do not constitute medical advice,
        diagnosis, or treatment.
    </p>
    <p>
        You should consult a qualified physician or healthcare provider before beginning any new
        exercise program, particularly if you:
    </p>
    <ul>
        <li>Have a pre-existing medical condition</li>
        <li>Are returning from injury or illness</li>
        <li>Have been inactive for an extended period</li>
        <li>Experience pain, discomfort, or unusual symptoms during training</li>
    </ul>
    <p>
        Your coach is a running coach, not a medical professional. Nothing communicated through the
        Platform should be interpreted as medical advice.
    </p>

    <h2>5. Assumption of Risk and Liability Waiver</h2>
    <p>
        Running and endurance training carry inherent risks, including but not limited to muscle
        strain, joint injury, cardiovascular stress, and in rare cases, serious injury or death. By
        using SimplyRunFaster, you acknowledge and accept these risks.
    </p>
    <p>
        To the fullest extent permitted by applicable law, you agree that SimplyRunFaster, Will Musto,
        and any coaches or staff associated with the Platform are not liable for:
    </p>
    <ul>
        <li>Any injury, illness, or adverse health outcome arising from following a training plan
            generated or approved through the Platform</li>
        <li>Any injury arising from failure to follow the training plan as prescribed</li>
        <li>Any inaccuracy in data provided by third-party platforms (Intervals.icu, Garmin, COROS,
            Polar, Suunto, Wahoo, or any other connected device or service)</li>
        <li>Any decision made by you to modify, ignore, or deviate from your prescribed training
            plan</li>
        <li>Any consequence of failing to disclose relevant medical history during onboarding or in
            communications with your coach</li>
    </ul>
    <p>
        This limitation of liability applies regardless of the legal theory under which a claim is
        brought, including negligence, breach of contract, or strict liability.
    </p>

    <h2>6. Return-to-Running Plans</h2>
    <p>
        If you select the return-to-running pathway (indicating you are returning from injury or a
        long break), you additionally agree that:
    </p>
    <ul>
        <li>You have been cleared by a qualified medical professional to return to running, OR you
            are returning from a non-injury break and do not require medical clearance</li>
        <li>You will immediately notify your coach if you experience any pain, discomfort, or adverse
            symptoms during the return-to-running progression</li>
        <li>The return-to-running plan is conservative by design and does not constitute medical
            clearance or rehabilitation advice</li>
        <li>SimplyRunFaster bears no liability for any re-injury or adverse outcome during the
            return-to-running period</li>
    </ul>

    <h2>7. Subscription and Billing</h2>
    <h3>7.1 Subscription</h3>
    <p>
        SimplyRunFaster is offered on a subscription basis. Current pricing is displayed at the time
        of purchase. By subscribing, you authorize us to charge your payment method on a recurring
        basis at the interval you select (monthly or annual).
    </p>
    <h3>7.2 Auto-Renewal</h3>
    <p>
        Subscriptions automatically renew at the end of each billing period unless cancelled before
        the renewal date. You will not receive a separate notice before each renewal charge.
    </p>
    <h3>7.3 Cancellation</h3>
    <p>
        You may cancel your subscription at any time through the billing section of your account
        settings. Cancellation takes effect at the end of the current billing period. You will retain
        access to the Platform until the end of the period for which you have paid. No partial refunds
        are provided for unused time within a billing period.
    </p>
    <h3>7.4 Refunds</h3>
    <p>
        All subscription fees are non-refundable except where required by applicable law. If you
        believe you have been charged in error, contact us at
        <a href="mailto:privacy@simplyrunfaster.com">privacy@simplyrunfaster.com</a> within 30 days of
        the charge.
    </p>
    <h3>7.5 Price Changes</h3>
    <p>
        We reserve the right to change subscription pricing with 30 days advance notice. Notice will
        be provided via email and in-app notification. Continued use of the Platform after a price
        change constitutes acceptance of the new pricing. Founding member pricing is locked for the
        life of the account as described at the time of purchase, and is not subject to general price
        increases.
    </p>
    <h3>7.6 Failed Payments</h3>
    <p>
        If a payment fails, we will notify you by email and push notification. You will have a 7-day
        grace period to update your payment information before access to the Platform is suspended. We
        are not liable for any interruption in service resulting from a failed payment.
    </p>
    <h3>7.7 Payment Processing</h3>
    <p>
        All payment processing is handled by Stripe, Inc. We do not store your payment card details.
        By subscribing, you also agree to Stripe's Terms of Service (stripe.com/terms).
    </p>

    <h2>8. Third-Party Integrations</h2>
    <p>
        SimplyRunFaster integrates with third-party platforms including Intervals.icu and payment
        processor Stripe. Use of these integrations is subject to the respective third parties' terms
        of service and privacy policies. We are not responsible for the availability, accuracy, or
        conduct of any third-party platform.
    </p>
    <p>
        Watch and activity data synced through Intervals.icu is provided on an as-is basis. We make no
        representations regarding the accuracy of data collected by GPS watches or other wearable
        devices, and training plan adjustments based on such data are made at the coach's discretion.
    </p>

    <h2>9. Athlete Responsibilities</h2>
    <p>You agree to:</p>
    <ul>
        <li>Provide accurate and complete information during onboarding and in all communications with
            your coach</li>
        <li>Communicate promptly with your coach if you experience injury, illness, or any change in
            your health or fitness status that may affect your training</li>
        <li>Use the Platform only for its intended purpose (personal running training)</li>
        <li>Not share your account credentials with any other person</li>
        <li>Not use the Platform to harass, threaten, or abuse any coach, staff member, or other
            user</li>
    </ul>

    <h2>10. Coach Responsibilities and Limitations</h2>
    <p>Your assigned coach will:</p>
    <ul>
        <li>Review and approve all algorithmically generated training plans before you see them</li>
        <li>Be available to respond to in-app messages within a reasonable timeframe (typically within
            48 hours on business days)</li>
        <li>Use their professional judgment to modify plans as needed based on your progress and
            feedback</li>
    </ul>
    <p>Your coach will not:</p>
    <ul>
        <li>Provide medical advice or diagnoses</li>
        <li>Guarantee specific performance outcomes</li>
        <li>Be available for real-time communication or emergency support</li>
    </ul>
    <p>
        SimplyRunFaster reserves the right to assign or reassign coaches at any time. You will be
        notified of any coach change.
    </p>

    <h2>11. Intellectual Property</h2>
    <p>
        All content on the Platform, including training plan templates, workout descriptions, coaching
        methodologies, and software, is the property of SimplyRunFaster or its licensors and is
        protected by applicable intellectual property laws. You may not reproduce, distribute, or
        create derivative works from any Platform content without our express written permission.
    </p>
    <p>
        Your personal training data remains yours. We do not claim ownership of data you provide or
        that is synced from your connected devices.
    </p>

    <h2>12. Privacy</h2>
    <p>
        Your use of the Platform is also governed by our
        <a href="/app/privacy">Privacy Policy</a>, available at simplyrunfaster.com/app/privacy. By
        using the Platform, you consent to the data practices described in the Privacy Policy.
    </p>

    <h2>13. Termination</h2>
    <p>
        We reserve the right to suspend or terminate your account at any time if you violate these
        Terms or engage in conduct we determine to be harmful to the Platform, other users, or our
        coaches. In the event of termination for cause, no refund will be provided for any unused
        subscription period.
    </p>
    <p>
        You may delete your account at any time by contacting
        <a href="mailto:privacy@simplyrunfaster.com">privacy@simplyrunfaster.com</a>. Account deletion
        is subject to the data retention terms described in the Privacy Policy.
    </p>

    <h2>14. Disclaimers</h2>
    <p>
        THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
        IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES INCLUDING
        WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
    </p>
    <p>
        WE DO NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR
        OTHER HARMFUL COMPONENTS.
    </p>

    <h2>15. Limitation of Liability</h2>
    <p>
        TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, SIMPLYRUNFASTER'S TOTAL LIABILITY TO YOU FOR
        ANY CLAIM ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE PLATFORM SHALL NOT
        EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.
    </p>
    <p>
        IN NO EVENT SHALL SIMPLYRUNFASTER BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
        CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA, OR PERSONAL INJURY,
        EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
    </p>
    <p>
        Some jurisdictions do not allow the exclusion or limitation of certain damages. In such
        jurisdictions, our liability is limited to the maximum extent permitted by law.
    </p>

    <h2>16. Governing Law and Dispute Resolution</h2>
    <p>
        These Terms are governed by the laws of the State of Tennessee, United States, without regard
        to conflict of law principles.
    </p>
    <p>
        Any dispute arising out of or relating to these Terms or your use of the Platform shall first
        be submitted to informal negotiation by contacting us at
        <a href="mailto:privacy@simplyrunfaster.com">privacy@simplyrunfaster.com</a>. If the dispute
        is not resolved within 30 days, it shall be resolved by binding arbitration administered by
        the American Arbitration Association under its Consumer Arbitration Rules, except that either
        party may bring claims in small claims court for disputes within that court's jurisdiction.
    </p>
    <p>
        <strong>Class action waiver:</strong> You agree to resolve disputes with us on an individual
        basis only and waive any right to participate in a class action lawsuit or class-wide
        arbitration.
    </p>
    <p>
        <strong>EU/UK users:</strong> Nothing in this section limits your rights under applicable EU or
        UK consumer protection law, including your right to bring claims before your local courts or
        regulatory authorities.
    </p>
    <p>
        <strong>Mexico users:</strong> Nothing in this section limits your rights under the Ley Federal
        de Protecci&oacute;n al Consumidor (LFPC).
    </p>

    <h2>17. Changes to These Terms</h2>
    <p>
        We may update these Terms from time to time. We will notify you of material changes by email
        and in-app notification at least 14 days before the changes take effect. Continued use of the
        Platform after the effective date constitutes acceptance of the updated Terms.
    </p>

    <h2>18. Contact</h2>
    <p>For any questions about these Terms:</p>
    <p>
        Email: <a href="mailto:privacy@simplyrunfaster.com">privacy@simplyrunfaster.com</a><br>
        Operator: Will Musto, SimplyRunFaster<br>
        Website: simplyrunfaster.com
    </p>
</main>
<?php include __DIR__ . '/../../views/layout/html_close.php'; ?>
